<a href="https://colab.research.google.com/github/h4ck4l1/datasets/blob/main/NLP_with_RNN_and_Attention/NMT_with_attention_google.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [203]:
import os,warnings,sys
if "google.colab" in sys.modules:
    !pip3 install -q -U "tensorflow-text==2.13.0"
    !pip3 install -q -U einops
warnings.filterwarnings("ignore")
from IPython.display import clear_output
os.environ["TF_MIN_LOG_LEVEL"] = "3"
import tensorflow as tf
from tensorflow import keras
import tensorflow_text as text
import typing
from zipfile import ZipFile
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import plotly.express as px
import plotly.io as pio
import einops
pio.templates.default = "plotly_dark"
import numpy as np
np.set_printoptions(precision=2)
tf.get_logger().setLevel("ERROR")
%xmode Minimal
if "google.colab" in sys.modules:
    clear_output()

In [204]:

class ShapeCheck():

    def __init__(self):

        self.shapes = {}

    def __call__(self,tensor,names,broadcast=False):

        parsed = einops.parse_shape(tensor,names)

        for name,new_dim in parsed.items():

            old_dim = self.shapes.get(name,None)

            if broadcast and (new_dim == 1):
                continue

            if old_dim is None:

                self.shapes[name] = new_dim
                continue

            if new_dim != old_dim:

                raise ValueError(f"SHAPE MISTMATCH FOR DIMENSION: '{name}' FOUND: {new_dim} EXPECTED: {old_dim}")

In [205]:
url = "http://storage.googleapis.com/download.tensorflow.org/data/spa-eng.zip"

In [206]:
file_path = keras.utils.get_file(fname="spa-eng.zip",origin=url,extract=True)

with ZipFile(file_path,"r") as f:

    f.extractall("spa-eng")

with open("spa-eng/spa-eng/spa.txt","r") as f:

    total_text = f.read()
    total_text = [line.split("\t") for line in total_text.splitlines()]
    en_text,es_text = zip(*total_text)

In [207]:
en_text[-1]

'If you want to sound like a native speaker, you must be willing to practice saying the same sentence over and over in the same way that banjo players practice the same phrase over and over until they can play it correctly and at the desired tempo.'

In [208]:
es_text[-1]

'Si quieres sonar como un hablante nativo, debes estar dispuesto a practicar diciendo la misma frase una y otra vez de la misma manera en que un músico de banjo practica el mismo fraseo una y otra vez hasta que lo puedan tocar correctamente y en el tiempo esperado.'

In [209]:
en_array = np.array(en_text)
es_array = np.array(es_text)

In [210]:
is_train = np.random.uniform(size=(len(en_array),)) < 0.8

raw_train = (
    tf.data.Dataset
    .from_tensor_slices((en_array[is_train],es_array[is_train]))
    .shuffle(len(en_text))
    .batch(64)
)
raw_valid = (
    tf.data.Dataset
    .from_tensor_slices((en_array[~is_train],es_array[~is_train]))
    .shuffle(len(en_text))
    .batch(64)
)

In [211]:
for en,es in raw_train.take(1):
    print(en[:4])
    print("translates to latin as ")
    print(es[:4])

tf.Tensor(
[b'This is very risky.' b'They abandoned the ship.'
 b'How much does it cost?' b"He didn't go to school."], shape=(4,), dtype=string)
translates to latin as 
tf.Tensor(
[b'Esto es muy arriesgado.' b'Abandonaron el barco.'
 b'\xc2\xbfCu\xc3\xa1nto cuesta eso?' b'No fue a clase.'], shape=(4,), dtype=string)


# Standardize Text

In [212]:
es_text[:10]

('Ve.',
 'Vete.',
 'Vaya.',
 'Váyase.',
 'Hola.',
 '¡Corre!',
 'Corred.',
 '¿Quién?',
 '¡Fuego!',
 '¡Incendio!')

In [213]:
tf.constant(es_text[:10]) # converting to tensor

<tf.Tensor: shape=(10,), dtype=string, numpy=
array([b'Ve.', b'Vete.', b'Vaya.', b'V\xc3\xa1yase.', b'Hola.',
       b'\xc2\xa1Corre!', b'Corred.', b'\xc2\xbfQui\xc3\xa9n?',
       b'\xc2\xa1Fuego!', b'\xc2\xa1Incendio!'], dtype=object)>

In [214]:
temp_text = text.normalize_utf8(es_text[:10],"NFKD") # Normalizing text so that it can be used in operations
temp_text

<tf.Tensor: shape=(10,), dtype=string, numpy=
array([b'Ve.', b'Vete.', b'Vaya.', b'Va\xcc\x81yase.', b'Hola.',
       b'\xc2\xa1Corre!', b'Corred.', b'\xc2\xbfQuie\xcc\x81n?',
       b'\xc2\xa1Fuego!', b'\xc2\xa1Incendio!'], dtype=object)>

In [215]:
temp_text_1 = tf.strings.lower(temp_text) # Lower casing all the characters
temp_text_1

<tf.Tensor: shape=(10,), dtype=string, numpy=
array([b've.', b'vete.', b'vaya.', b'va\xcc\x81yase.', b'hola.',
       b'\xc2\xa1corre!', b'corred.', b'\xc2\xbfquie\xcc\x81n?',
       b'\xc2\xa1fuego!', b'\xc2\xa1incendio!'], dtype=object)>

In [216]:
temp_text_2 = tf.strings.regex_replace(temp_text_1,"[^ a-z.?!,¿]","")  # [^ ...] means exclude..so excluding all the a-z and rest
temp_text_2                                                            # and replacing with noting

<tf.Tensor: shape=(10,), dtype=string, numpy=
array([b've.', b'vete.', b'vaya.', b'vayase.', b'hola.', b'corre!',
       b'corred.', b'\xc2\xbfquien?', b'fuego!', b'incendio!'],
      dtype=object)>

In [217]:
temp_text_3 = tf.strings.regex_replace(temp_text_2,"[.¡¿,?!]",r' \0 ') # Placing a null character[raw_string : r'']
temp_text_3                                                            # before and after every punctuation

<tf.Tensor: shape=(10,), dtype=string, numpy=
array([b've . ', b'vete . ', b'vaya . ', b'vayase . ', b'hola . ',
       b'corre ! ', b'corred . ', b' \xc2\xbf quien ? ', b'fuego ! ',
       b'incendio ! '], dtype=object)>

In [218]:
temp_text_4= tf.strings.strip(temp_text_3) # stripping any extra spaces
temp_text_4

<tf.Tensor: shape=(10,), dtype=string, numpy=
array([b've .', b'vete .', b'vaya .', b'vayase .', b'hola .', b'corre !',
       b'corred .', b'\xc2\xbf quien ?', b'fuego !', b'incendio !'],
      dtype=object)>

In [219]:
temp_text_5 = tf.strings.join(['[startofsequence]',temp_text_4,'[endofsequence]'],separator=" ")
temp_text_5

<tf.Tensor: shape=(10,), dtype=string, numpy=
array([b'[startofsequence] ve . [endofsequence]',
       b'[startofsequence] vete . [endofsequence]',
       b'[startofsequence] vaya . [endofsequence]',
       b'[startofsequence] vayase . [endofsequence]',
       b'[startofsequence] hola . [endofsequence]',
       b'[startofsequence] corre ! [endofsequence]',
       b'[startofsequence] corred . [endofsequence]',
       b'[startofsequence] \xc2\xbf quien ? [endofsequence]',
       b'[startofsequence] fuego ! [endofsequence]',
       b'[startofsequence] incendio ! [endofsequence]'], dtype=object)>

In [220]:
def text_preprocessor(input_text):

    input_text = text.normalize_utf8(input_text,"NFKD")
    input_text = tf.strings.lower(input_text)
    input_text = tf.strings.regex_replace(input_text,"[^ a-z?.!¿¡,]","")
    input_text = tf.strings.regex_replace(input_text,"[?.!¿¡,]",r" \0 ")
    input_text = tf.strings.strip(input_text)
    input_text = tf.strings.join(["[startofsequence]",input_text,"[endofsequence]"],separator=" ")
    return input_text

# Text Vectorization of En and Es

In [221]:
vocab_size = 5000

en_vec_layer = keras.layers.TextVectorization(vocab_size,standardize=text_preprocessor,ragged=True)
en_vec_layer.adapt(raw_train.map(lambda en,es:en))
es_vec_layer = keras.layers.TextVectorization(vocab_size,standardize=text_preprocessor,ragged=True)
es_vec_layer.adapt(raw_train.map(lambda en,es:es))

In [222]:
print(en_vec_layer.get_vocabulary()[:10])
print(es_vec_layer.get_vocabulary()[:10])

['', '[UNK]', '[startofsequence]', '[endofsequence]', '.', 'the', 'i', 'to', 'you', 'tom']
['', '[UNK]', '[startofsequence]', '[endofsequence]', '.', 'que', 'de', 'el', 'a', 'no']


In [223]:
for english_text,en_vectorized_out in zip(en.numpy()[:4],en_vec_layer(en[:4])):
    print(english_text,"---->",en_vectorized_out)

b'This is very risky.' ----> tf.Tensor([   2   22   12   56 3217    4    3], shape=(7,), dtype=int64)
b'They abandoned the ship.' ----> tf.Tensor([   2   52 1730    5  869    4    3], shape=(7,), dtype=int64)
b'How much does it cost?' ----> tf.Tensor([  2  54 107 133  17 757  11   3], shape=(8,), dtype=int64)
b"He didn't go to school." ----> tf.Tensor([  2  13  64  45   7 141   4   3], shape=(8,), dtype=int64)


In [224]:
for latin_text,es_vectorized_out in zip(es.numpy()[:4],es_vec_layer(es[:4])):
    print(latin_text,"---->",es_vectorized_out)

b'Esto es muy arriesgado.' ----> tf.Tensor([   2   58   15   42 3972    4    3], shape=(7,), dtype=int64)
b'Abandonaron el barco.' ----> tf.Tensor([   2 4625    7  782    4    3], shape=(6,), dtype=int64)
b'\xc2\xbfCu\xc3\xa1nto cuesta eso?' ----> tf.Tensor([  2  13 152 707  44  12   3], shape=(7,), dtype=int64)
b'No fue a clase.' ----> tf.Tensor([  2   9  50   8 251   4   3], shape=(7,), dtype=int64)


In [225]:
en_vocab = np.array(en_vec_layer.get_vocabulary())
es_vocab = np.array(es_vec_layer.get_vocabulary())

In [226]:
print(" ".join(en_vocab[en_vectorized_out.numpy()]))
print(" ".join(es_vocab[es_vectorized_out.numpy()]))

[startofsequence] he didnt go to school . [endofsequence]
[startofsequence] no fue a clase . [endofsequence]


In [227]:
en_vec_out = en_vec_layer(en)
es_vec_out = es_vec_layer(es)

In [228]:
fig = make_subplots(cols=2,subplot_titles=["Unmasked","Masked"])
fig.add_trace(go.Heatmap(z=en_vec_out.to_tensor().numpy()),row=1,col=1)
fig.add_trace(go.Heatmap(z=np.array((en_vec_out.to_tensor() != 0).numpy(),dtype=np.int32)),row=1,col=2)
fig.show()

In [229]:
def preprocess_dataset(en,es):
    X_train = en_vec_layer(en).to_tensor()
    X_dec = es_vec_layer(es)
    X_dec_train = X_dec[:,:-1].to_tensor()
    y_train = X_dec[:,1:].to_tensor()

    return (X_train,X_dec_train),y_train

In [230]:
train_ds = raw_train.map(preprocess_dataset,tf.data.AUTOTUNE)
valid_ds = raw_valid.map(preprocess_dataset,tf.data.AUTOTUNE)

In [231]:
for (en_in,es_in),es_out in train_ds.take(1):
    print(en_in.shape)
    print(es_in.shape)
    print(es_out.shape)

(64, 16)
(64, 16)
(64, 16)


# Encoder Class

- Embedding Layer
- GRU/LSTM Layer

In [232]:
vocab_size = len(en_vec_layer.get_vocabulary())
vocab_size

5000

In [233]:
embed_size = 256

In [234]:
encoder_embed_layer = keras.layers.Embedding(vocab_size,embed_size,mask_zero=True)
encoder = keras.layers.Bidirectional(
    keras.layers.LSTM(256,return_sequences=True,recurrent_initializer="glorot_uniform"),
    merge_mode="sum"
)

In [235]:
shape_checker = ShapeCheck()
shape_checker(en_in,"batch s")

In [236]:
shape_checker.shapes

{'batch': 64, 's': 16}

In [237]:
enc_embed_output = encoder_embed_layer(en_in)
enc_embed_output.shape

TensorShape([64, 16, 256])

In [238]:
shape_checker(enc_embed_output,"batch s units")
shape_checker.shapes

{'batch': 64, 's': 16, 'units': 256}

In [239]:
encoder_outputs = encoder(enc_embed_output)
encoder_outputs.shape

TensorShape([64, 16, 256])

In [240]:
shape_checker(encoder_outputs,"batch s units")

In [241]:
mha = keras.layers.MultiHeadAttention(num_heads=1,key_dim=256)

In [242]:
print(en_in.shape)
print(encoder_outputs.shape)

(64, 16)
(64, 16, 256)


In [243]:
len(en_vec_layer.get_vocabulary())

5000

In [244]:
class Encoder(keras.Model):

    def __init__(self,units=256,vec_layer=en_vec_layer,**kwargs):

        super(Encoder,self).__init__(**kwargs)
        self.vec_layer = vec_layer
        self.embed = keras.layers.Embedding(vec_layer.vocabulary_size(),units,mask_zero=True)
        self.Rnn = keras.layers.Bidirectional(
            layer=keras.layers.LSTM(units,return_sequences=True,return_state=True,recurrent_initializer="glorot_uniform"),
            merge_mode="sum"
        )

    def call(self,inputs):

        shape_checker = ShapeCheck()
        shape_checker(inputs,"batch s")
        z = self.embed(inputs)
        shape_checker(z,"batch s units")
        z,*encoder_state = self.Rnn(z)
        self.encoder_state = encoder_state
        shape_checker(z,"batch s units")
        return z


# CrossAttention

In [245]:
decoder_embed_layer = keras.layers.Embedding(es_vec_layer.vocabulary_size(),256,mask_zero=True)
decoder_embed_out = decoder_embed_layer(es_in)
decoder_embed_out.shape

TensorShape([64, 16, 256])

In [246]:
mha = keras.layers.MultiHeadAttention(num_heads=1,key_dim=256)
attention_output,attention_scores = mha(query=decoder_embed_out,value=encoder_outputs,return_attention_scores=True)
print(attention_output.shape)
print(attention_scores.shape)

(64, 16, 256)
(64, 1, 16, 16)


In [247]:
shape_checker = ShapeCheck()
shape_checker(decoder_embed_out,"batch t units")
shape_checker(encoder_outputs,"batch s units")

In [248]:
attention_scores = tf.reduce_mean(attention_scores,axis=1)
attention_scores.shape

TensorShape([64, 16, 16])

In [249]:
adding_layer = keras.layers.Add()
add_out = adding_layer([decoder_embed_out,attention_output])
add_out.shape

TensorShape([64, 16, 256])

In [250]:
layer_norm = keras.layers.LayerNormalization()
layer_out = layer_norm(add_out)
layer_out.shape

TensorShape([64, 16, 256])

In [251]:
class CrossAttention(keras.layers.Layer):

    def __init__(self,units=256,**kwargs):

        super(CrossAttention,self).__init__(**kwargs)
        self.mha = keras.layers.MultiHeadAttention(num_heads=1,key_dim=units)
        self.add = keras.layers.Add()
        self.layer_norm = keras.layers.LayerNormalization()

    def call(self,decoder_out,encoder_out):

        shape_checker = ShapeCheck()
        shape_checker(decoder_out,"batch t units")
        shape_checker(encoder_out,"batch s units")

        attention_output,attention_scores = self.mha(query=decoder_out,value=encoder_out,return_attention_scores=True)
        shape_checker(attention_output,"batch t units")
        shape_checker(attention_scores,"batch heads t s")

        add_and_layer_norm = self.layer_norm(self.add([decoder_out,attention_output]))
        self.attention_scores = tf.reduce_mean(attention_scores,axis=1)

        return add_and_layer_norm

In [252]:
attention_layer = CrossAttention()

attention_out = attention_layer(decoder_embed_out,encoder_outputs)
attention_out.shape

TensorShape([64, 16, 256])

In [253]:
attention_layer.attention_scores.shape

TensorShape([64, 16, 16])

In [254]:
np.sum(attention_layer.attention_scores,axis=-1)[:5,:]

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],
      dtype=float32)

In [255]:
fig = make_subplots(cols=2,subplot_titles=["Attention Output","Masked Output"])
fig.add_trace(go.Heatmap(z=attention_layer.attention_scores[:,0,:]),row=1,col=1)
fig.add_trace(go.Heatmap(z=np.array((en_vec_out.to_tensor() != 0).numpy(),dtype=np.int32)),row=1,col=2)
fig.show()

# Decoder

In [307]:
class Decoder(keras.layers.Layer):

    def __init__(self,units=256,vec_layer=es_vec_layer,**kwargs):

        super(Decoder,self).__init__(**kwargs)

        '''Preprocessing Section'''
        self.vec_layer = vec_layer
        self.vocab_size = vec_layer.vocabulary_size()
        self.word_to_id = keras.layers.StringLookup(
            vocabulary=vec_layer.get_vocabulary(),
            oov_token="[UNK]",
            mask_token=""
        )
        self.id_to_word = keras.layers.StringLookup(
            vocabulary=vec_layer.get_vocabulary(),
            oov_token="[UNK]",
            mask_token="",
            invert=True
        )
        self.start_token = self.word_to_id('[startofsequence]')
        self.end_token = self.word_to_id('[endofsequence]')
        self.units = units


        '''Model Layers section'''
        self.es_embed = keras.layers.Embedding(vec_layer.vocabulary_size(),units,mask_zero=True)
        self.decoder_cell = keras.layers.LSTM(units,return_sequences=True,return_state=True,recurrent_initializer="glorot_uniform")
        self.attention = CrossAttention()
        self.out = keras.layers.Dense(vec_layer.vocabulary_size())


    def call(self,encoder_outputs,decoder_inputs,encoder_state=None,return_state=False):

        shape_checker = ShapeCheck()
        shape_checker(encoder_outputs,"batch s units")
        shape_checker(decoder_inputs,"batch t")
        if encoder_state is not None:
            shape_checker(encoder_state[0],"batch units")
            shape_checker(encoder_state[1],"batch units")

        es_embed_out = self.es_embed(decoder_inputs)
        shape_checker(es_embed_out,"batch t units")



        decoder_outputs,*decoder_state = self.decoder_cell(es_embed_out,initial_state=encoder_state)
        shape_checker(decoder_outputs,"batch t units")
        shape_checker(decoder_state[0],"batch units")
        shape_checker(decoder_state[1],"batch units")

        attention_out = self.attention(decoder_outputs,encoder_outputs)
        shape_checker(attention_out,"batch t units")
        shape_checker(self.attention.attention_scores,"batch t s")

        total_out = self.out(attention_out)

        if return_state:
            return total_out,decoder_state
        else:
            return total_out


    def get_initial_state(self,encoder_outputs):
        batch_size = tf.shape(encoder_outputs)[0]
        start_tokens = tf.fill(dims=[batch_size,1],value=self.start_token)
        done = tf.zeros(shape=[batch_size,1],dtype=tf.bool)
        embedding = self.es_embed(start_tokens)
        return start_tokens,done,self.decoder_cell.get_initial_state(embedding)


    def tokens_to_text(self,tokens):
        text_ = self.id_to_word(tokens)
        text_ = tf.strings.reduce_join(text_,axis=-1,separator=" ")
        text_ = tf.strings.regex_replace(text_,"^ *\[startofsequence\] *","")
        text_ = tf.strings.regex_replace(text_," *\[endofsequence\] *$","")
        return text_

    def get_next_tokens(self,encoder_outputs,next_token,done,state,temperature=0.0):
        total_output,state = self(encoder_outputs,next_token,encoder_state=state,return_state=True)

        if temperature:
            next_token = tf.argmax(total_output,axis=-1)
        else:
            scaled_out = total_output/temperature
            next_token = tf.random.categorical(scaled_out[:,-1,:],num_samples=1,seed=42)

        done = done | (next_token == self.end_token)
        next_token = tf.where(done,tf.constant(0,dtype=tf.int64),next_token)
        return next_token,done,state

In [308]:
decoder = Decoder()

In [309]:
next_token,done,state = decoder.get_initial_state(encoder_outputs)
tokens_list = []

for i in range(10):

    next_token,done,state = decoder.get_next_tokens(encoder_outputs,next_token,done,state,temperature=1)
    tokens_list.append(next_token)

In [316]:
decoder.tokens_to_text(tf.concat(tokens_list,axis=-1))[:3]

<tf.Tensor: shape=(3,), dtype=string, numpy=
array([b'bancos caliente junto titulo creas asesino vista alergica me me',
       b'bancos caliente junto titulo creas demostrar sensacion pusimos pelos mudo',
       b'caliente gracias idioma tierra cero cero cero equipos vienes buscar'],
      dtype=object)>

# Translator Total Model

In [ ]:
class Translator(keras.Model):
    @classmethod
    def add_method(cls,func):
        setattr(cls,func.__name__,func)
        return func

    def __init__(self,units=256,en_vec_layer,es_vec_layer,**kwargs):

        super(Translator,self).__init__(**kwargs)

        self.encoder = Encoder(units=units,en_vec_layer)
        self.decoder = Decoder(units=units,es_vec_layer)


    def call(self,inputs):

        encoder_inputs,decoder_inputs = inputs

        encoder_outputs = self.encoder(encoder_inputs)
        total_out = self.decoder(encoder_ouputs,decoder_inputs)
        return total_out